In [ ]:
import pandas as pd
import numpy as np


np.random.seed(42)
n_rows = 500

data = {
    'Order_ID': range(1001, 1001 + n_rows),
    'Date': pd.date_range(start='2025-01-01', periods=n_rows, freq='h'),
    'Product': np.random.choice(['Laptop', 'Headphones', 'Smart Watch', 'Monitor', 'Keyboard'], size=n_rows),
    'Quantity': np.random.randint(1, 6, size=n_rows),
    'Unit_Price': np.random.choice([1200, 150, 300, 450, 80], size=n_rows),
    'Customer_Region': np.random.choice(['Riyadh', 'Jeddah', 'Dammam', 'Mecca'], size=n_rows)
}

df = pd.DataFrame(data)

#نضيف اخطاء متعمدين عشان ننضفها بعدين
df.loc[df.sample(frac=0.04).index, 'Quantity'] = np.nan

# نعرض اول 5 اسطر
df.head()

,Order_ID,Date,Product,Quantity,Unit_Price,Customer_Region
0,1001,2025-01-01 00:00:00,Monitor,4.0,450,Mecca
1,1002,2025-01-01 01:00:00,Keyboard,1.0,450,Mecca
2,1003,2025-01-01 02:00:00,Smart Watch,5.0,450,Jeddah
3,1004,2025-01-01 03:00:00,Keyboard,3.0,450,Mecca
4,1005,2025-01-01 04:00:00,Keyboard,3.0,80,Dammam

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         500 non-null    int64
 1   Date             500 non-null    datetime64[ns]
 2   Product          500 non-null    object
 3   Quantity         480 non-null    float64
 4   Unit_Price       500 non-null    int64
 5   Customer_Region  500 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 23.6+ KB

In [ ]:
df.isnull().sum()

Order_ID            0
Date                0
Product             0
Quantity           20
Unit_Price          0
Customer_Region     0
dtype: int64

In [ ]:
df.describe()

          Order_ID                 Date    Quantity  Unit_Price
count   500.000000                  500  480.000000     500.000
mean   1250.500000  2025-01-11 09:30:00    3.068750     436.520
min    1001.000000  2025-01-01 00:00:00    1.000000      80.000
25%    1125.750000  2025-01-06 04:45:00    2.000000     150.000
50%    1250.500000  2025-01-11 09:30:00    3.000000     300.000
75%    1375.250000  2025-01-16 14:15:00    4.000000     450.000
max    1500.000000  2025-01-21 19:00:00    5.000000    1200.000
std     144.481833                  NaN    1.436717     414.806

In [ ]:
# الان راح نستبدل القيم المفقودة بالوسيط
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())

#الان راح نتاكد
df.isnull().sum()

Order_ID           0
Date               0
Product            0
Quantity           0
Unit_Price         0
Customer_Region    0
dtype: int64

In [ ]:
#الان بنحسب الاجمالي
df['Total_Sales'] = df['Quantity'] * df['Unit_Price']

df.head()

,Order_ID,Date,Product,Quantity,Unit_Price,Customer_Region,Total_Sales
0,1001,2025-01-01 00:00:00,Monitor,4.0,450,Mecca,1800.0
1,1002,2025-01-01 01:00:00,Keyboard,1.0,450,Mecca,450.0
2,1003,2025-01-01 02:00:00,Smart Watch,5.0,450,Jeddah,2250.0
3,1004,2025-01-01 03:00:00,Keyboard,3.0,450,Mecca,1350.0
4,1005,2025-01-01 04:00:00,Keyboard,3.0,80,Dammam,240.0

In [ ]:
# الان بنشوف اجمالي المبيعات حسب المدن
sales_by_region = df.groupby('Customer_Region')['Total_Sales'].sum().sort_values(ascending=False)
print("إجمالي المبيعات على حسب المدينة:")
print(sales_by_region)

إجمالي المبيعات على حسب المدينة:
Customer_Region
Mecca     209010.0
Jeddah    188810.0
Dammam    163500.0
Riyadh    149420.0
Name: Total_Sales, dtype: float64

In [ ]:
#الان بنحسب اجمالي المبيعات حسب المنتج
sales_by_product = df.groupby('Product')['Total_Sales'].sum().sort_values(ascending=False)
print("إجمالي المبيعات على حسب المنتج:")
print(sales_by_product)

إجمالي المبيعات على حسب المنتج:
Product
Headphones     154150.0
Monitor        151950.0
Laptop         150500.0
Keyboard       147300.0
Smart Watch    106840.0
Name: Total_Sales, dtype: float64

In [ ]:
#الان بنحفظ البيانت الي نظفناها في ملف csv
df.to_csv('Cleand_Sales_Data.csv',index=False)